dataset_config:
  okvqa:
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased # TODO: add distilbert also?
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
